"""add enum for messagerole

Revision ID: 602e0f5dec7c
Revises: 2ffe1836707c
Create Date: 2026-04-22 17:21:43.118156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602e0f5dec7c'
down_revision: Union[str, Sequence[str], None] = '2ffe1836707c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type manually
    message_role = sa.Enum('user', 'assistant', name='messagerole')
    message_role.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('user', 'assistant', name='messagerole'),
        existing_nullable=False,
        postgresql_using='role::messagerole')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
        existing_type=sa.Enum('user', 'assistant', name='messagerole'),
        type_=sa.VARCHAR(),
        existing_nullable=False)
    # ### end Alembic commands ###

    # Drop the enum type manually
    message_role = sa.Enum('user', 'assistant', name='messagerole')
    message_role.drop(op.get_bind())
